version: '3.1'
services:
  app:
    container_name: springboot-postgres-docker
    image: springboot-postgres-docker
    build: ./
    ports:
      - "8080:8080"
    networks:
      - bootapp
networks:
  bootapp: